### ISSUE TITLE
Update Jenkins app to the latest version

### ISSUE THREAD

**Issue by aakashnagpal4567** [civo/kubernetes-marketplace#475]
This issue is a:
* [ ] Bug Report
* [x] Enhancement suggestion
* [ ] Feature request

If the issue concerns an existing Marketplace application, please tag the maintainer of the application (found in `manifest.yaml`) below:

## Enhancement suggestions / feature requests
Currently, we have Jenkins version 2.289.3 installed by Civo marketplace as a newer version 2.401.2 is available, so it needs to be updated to the newer version. We kindly request an update to the latest version of Jenkins on the Civo marketplace to ensure that we have access to the most recent features and improvements.

@dirien is the maintainer for this app, so I request you to please take a look into this.

**Comment by dirien** [comment]
LGTM!

**Comment by olblak** [comment]
This issue is now solved 
* https://github.com/civo/kubernetes-marketplace/blob/702e59cc389efcd4510db4ca8f7a3bd123a29796/jenkins/manifest.yaml#L3

And there is now an "updatecli" manifest to monitor newer version 
* [Updatecli Manifest](https://github.com/civo/kubernetes-marketplace/blob/master/.github/updatecli/updatecli.d/jenkins.yaml)
* [Recent automated pullrequest](https://github.com/civo/kubernetes-marketplace/pull/506)

**Comment by NerdyShawn** [comment]
@saiyam1814 We can close this one out updatecli is handling this now
- https://github.com/civo/kubernetes-marketplace/pull/504

**Comment by NerdyShawn** [comment]
cc: @kunal-kushwaha
